package spin:up@3.5.0;

/// The full world of a guest targeting an http-trigger
world http-trigger {
  include platform;
  export wasi:http/handler@0.3.0-rc-2025-08-15;
}

interface next {
  use wasi:http/types@0.3.0-rc-2025-08-15.{request, response, error-code};
  handle: async func(request: request) -> result<response, error-code>;
}

world http-middleware {
  include http-trigger;
  import next;
}

/// The imports needed for a guest to run on a Spin host
world platform {
  include fermyon:spin/platform@2.0.0;
  include wasi:keyvalue/imports@0.2.0-draft2;
  import spin:postgres/postgres@3.0.0;
  import spin:postgres/postgres@4.0.0;
  import spin:sqlite/sqlite@3.0.0;
  import wasi:config/store@0.2.0-draft-2024-09-27;
}
